# Generated by Django 2.0.9 on 2019-12-10 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtools', '0003_auto_20160128_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pay_for', models.BooleanField(verbose_name='Payment For')),
                ('currency', models.CharField(max_length=225, verbose_name='Currency')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('card_number', models.IntegerField(verbose_name='Card Number')),
                ('card_verif_number', models.IntegerField(verbose_name='Card Verification Number')),
                ('card_company', models.CharField(max_length=225, verbose_name='Card Company')),
                ('phone_number', models.IntegerField(verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
