# Generated by Django 2.0.9 on 2019-12-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_Birth',
            field=models.DateField(default='1999-12-12', verbose_name='Date Of Birth'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep_option',
            field=models.TextField(choices=[('Default', '---------'), ('ENG', 'Engineering'), ('MTH', 'Mathematics'), ('ECN', 'Economics')], default='Engineering', verbose_name='Option'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='matric_number',
            field=models.TextField(default='CSC/2014/087', help_text='CSC/****/***', verbose_name='Matric Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='part',
            field=models.TextField(choices=[('Default', '---------'), ('Part 1', '100 Level'), ('Part 2', '200 Level'), ('Part 3', '300 Level'), ('Part 4', '400 Level'), ('Part 5', '500 Level')], default='500 Level', verbose_name='Level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.TextField(default='+234 ', max_length=11, verbose_name='Contact'),
        ),
    ]
